### ISSUE TITLE
Remove indirect WDK dependency

### ISSUE THREAD

**Issue by lenny-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1105]
The loader added a dependency on the WDK previously. The known good is still set to revision where the loader can be built without a WDK, but this dependency will be a problem when updating known good or when building a loader separately. Based on today's discussion in the system integration conference call, it sounds like there are two main ways to address this. Both solutions center on removing the requirement for a loader build:

- Include a binary file in this repo, meaning that on Windows no is need need to do a loader build. This solution is implemented in PR #1098
- Remove the loader dependency by modifying the layer tests (the only component that needs the loader) to get function pointers at runtime, rather than resolving symbols at link time.

The first option is the simpler one, but checking binaries into a repo isn't the cleanest solution. The second option is probably a better solution, but it requires reworking some of the test code in this repo to build dispatch tables and call into Vulkan using those. Honestly, that's probably what they should be doing anyway.

Note that this issue also extends to the Vulkan-Tools repo, and I have a pull request open in that repo as KhronosGroup/Vulkan-Tools#231.

**Comment by lenny-lunarg** [comment]
I've merged the PRs that I previously linked to. That means that the other repos should no longer have a dependency on the WDK. If we want to change the logic so that the layers don't require a loader at all, we could change this issue to cover that issue. If we don't consider that important, we could also close this issue as being resolved.

**Comment by lenny-lunarg** [comment]
Closing this issue as the WDK dependency has been lifted.

**Comment by nsubtil** [comment]
This doesn't really help for the OneTree build, as it still requires a loader to be installed in the system in order to run VL tests, which is problematic (especially for CI).

Based on @lenny-lunarg's earlier comments, it sounds like modifying the tests to not rely on the loader would be a better approach anyway. Can we do that?

**Comment by KarenGhavam-lunarG** [comment]
Using the loader while running validation tests is also good testing of the loader that we currently rely upon. 

Yes, there is a way to modify the tests to not use the loader. That would take some significant development and would take some time. Would first want to know that this doesn’t compromise QA.

The validation layer tests without some real hardware underneath them (CI environment?) is not a complete test. You can do this with the mock ICD.

**Comment by nsubtil** [comment]
How can we figure out if modifying the tests would affect QA? If testing of VL + loader is used to verify the loader, I imagine that a compile-time switch could be created for this.

Mock ICD by itself won't help as it still requires a loader, so the WDK dependency is still present. OneTree needs to test VL without involving the WDK. Another way to achieve this could be to allow the loader to build without the WDK if it's not present.

**Comment by KarenGhavam-lunarG** [comment]
It was my understanding that the way Lenny resolved this issue does not require WDK to be on the system (removed the WDK dependency). He did this by including a binary on the system to remove the need for WDK being on the system. So OneTree can use the loader without having WDK on the system. That is my limited understanding and we can wait for Lenny to correct my understanding if needed.

**Comment by lenny-lunarg** [comment]
> it sounds like modifying the tests to not rely on the loader would be a better approach anyway. Can we do that?

Do you mean removing the build-time dependency? If so my answer is yes, absolutely. Or do you mean removing the run-time dependency? If so, no that has no chance of working. There's nothing capable of loading the layers at all if there's no loader.

As far as QA concerns go, we run the validation layer tests against the loader's tip of master every time we push a change to the loader in LunarG's internal testing, and that's also a part of our pre-merge testing. So I don't think QA is a big concern.

As for what @nsubtil mentioned, I don't see why this is a problem for OneTree. Your Vulkan driver should be installing a loader to the system because the driver doesn't work without the loader. On Windows systems the driver drops `vulkan-1.dll` into `System32` and probably`SysWOW64` as well. If installing linux drivers through a package, they should have a dependency one a specific version of the loader. So if you have a system where you've installed a driver and you don't have a loader, I would argue that the real problem is that the driver needed to install the loader. It's possible that such a system exists on Linux, especially given the enormous number of configurations out there, but I haven't seen cases where people have reported problems around this. Even then, the WDK dependency is irrelevant on Linux. So my thinking is that if the WDK dependency is a problem, simply stop building the loader and rely on the loader that your driver installed to `System32`. This is exactly how the validation tests work right now.

**Comment by mark-lunarg** [comment]
Coincidentally, I have had this branch sitting around for a few weeks, so I've created PR #1277.  This allows VVL to be built and tested without pulling down and building a loader.  This needs to be accompanied by supporting changes in the Google and LunarG internal CI systems.

**Comment by mark-lunarg** [comment]
Build-time dependencies on Vulkan-Loader have been removed from Vulkan-ValidationLayers.

**Comment by mark-lunarg** [comment]
Hey @lenny-lunarg, can you close this if the actionable items have been completed?
