### ISSUE TITLE
"... has no matching release barrier queued for execution." is very (maybe too) persistent!

### ISSUE THREAD

**Issue by Xeais** [KhronosGroup/Vulkan-ValidationLayers#2862]
### Describe the Issue
I am not entirely sure if this is a validation layer issue or something strange on my side. Fact is I have tried about everything and  the following validation error still remains. I am running out of ideas ...
### Valid Usage ID
> Validation[0]: Validation Error: [ UNASSIGNED-VkBufferMemoryBarrier-buffer-00004 ] Object 0: handle = 0x22a09433dd8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x991fd38f | vkQueueSubmit(): in submitted command buffer VkBufferMemoryBarrier acquiring ownership of VkBuffer (VkBuffer 0xe8fc2b0000000187[]), from srcQueueFamilyIndex 1 to dstQueueFamilyIndex 0 has no matching release barrier queued for execution.

### Environment:
 - OS: Windows 10
 - GPU: GTX 980M
 - SDK or header version if building from repo: **1.2.176.1**
 - Options enabled (synchronization, best practices, etc.): Nothing that should matter for this case.

### Additional context
- Parameters are matching (from `VkBufferMemoryBarrier`: `srcQueueFamilyIndex`, `dstQueueFamilyIndex`, `buffer`, `offset` and `size` as well as `srcStageMask` and `dstStageMask` from `vkCmdPipelineBarrier()`).
- The release barrier is submitted before the acquisition barrier.
- The releasing queue is signaling a semaphore that the acquiring queue will wait for.
- I even fiddled with `srcAccessMask` and `dstAccessMask` (also from `VkBufferMemoryBarrier`).
- Etc.

**Comment by ncesario-lunarg** [comment]
Thanks for the issue @Xeais, is there any chance you could provide a code sample? If there is an issue in the validation layers, we'll need that to create a test case to validate the fix. Vulkan synchronization is exceedingly tricky...

**Comment by Xeais** [comment]
> Thanks for the issue @Xeais, is there any chance you could provide a code sample? If there is an issue in the validation layers, we'll need that to create a test case to validate the fix. Vulkan synchronization is exceedingly tricky...

The whole project isn't particularly small, but I could lay out the parts relevant to the problem.

**Comment by Xeais** [comment]
@ncesario-lunarg Code is here - an update, too?

**Comment by ncesario-lunarg** [comment]
Thanks @Xeais! Sorry, the previous notification slipped by me. I don't see anything glaringly obvious, but I'll get to this more on Monday.

**Comment by Xeais** [comment]
@ncesario-lunarg Very well, thank you for the fast response and your Monday-time.

**Comment by ncesario-lunarg** [comment]
After re-reading some of the spec regarding [queue ownership](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-queue-transfers), I'm not sure queue ownership is being transferred correctly here, which could be part of the problem. Is the VUID happening in both the "multi-queue" _and_ "single-queue" cases?

It looks like `BeforeTransfer` is meant to transfer queue ownership from the graphics queue to the transfer queue. From my understanding, there should be 2 queue submissions there:
- One on the "source" queue to release ownership
- One on the "destination" queue to acquire ownership

Instead, it looks like the first `BeforeTransfer` adds a single barrier to the transfer command buffer and I only see one queue submission. Also, for the "transfer barrier," it looks like the "destination queue" is the graphics queue, but I would have thought that should be the transfer queue.

I'm going to tag one of our resident synchronization experts @jeremyg-lunarg as there's a very good chance I'm getting this wrong.

**Comment by jeremyg-lunarg** [comment]
I think `BeforeTransfer ` is being called in the wrong place. It should be after the last command on the transfer queue that uses the buffers.  That is:
```
  // this is too soon: m_allocation.BeforeTransfer(commandBufferTransfer);

  const uint64_t verticesBytes {sizeof(Vertex) * m_allocation.GetNumVertices()};
  const uint64_t indicesBytes {sizeof(uint32_t) * m_allocation.GetNumIndices()};
		
  const VkBufferCopy vertexBufferCopy {0, m_allocation.GetVertexOffset() * sizeof(Vertex), verticesBytes};
  commandBufferTransfer.CopyBuffer(srcBuffer, m_allocation.GetVertexBuffer(), vertexBufferCopy);
		
  const VkBufferCopy indexBufferCopy {verticesBytes, m_allocation.GetIndexOffset() * sizeof(uint32_t), indicesBytes};
  commandBufferTransfer.CopyBuffer(srcBuffer, m_allocation.GetIndexBuffer(), indexBufferCopy);

  m_allocation.BeforeTransfer(commandBufferTransfer); // call here instead!

```

Also you'll need similar GRAPHICS -> TRANSFER barriers before the copy operations if the buffers are constantly circulating between the 2 queues. This would happen at the original `BeforeTransfer `call site. I think I'm just rewording what Nate said above though.

**Comment by Xeais** [comment]
@ncesario-lunarg, @jeremyg-lunarg I have updated the code above (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2862#issuecomment-854200032) with the changes I made. Unfortunately, the error has not really changed:
> Validation[0]: Validation Error: [ UNASSIGNED-VkBufferMemoryBarrier-buffer-00004 ] Object 0: handle = 0x1674c233ff8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x991fd38f | vkQueueSubmit(): in submitted command buffer VkBufferMemoryBarrier acquiring ownership of VkBuffer (VkBuffer 0x2304970000000186[]), from srcQueueFamilyIndex 1 to dstQueueFamilyIndex 0 has no matching release barrier queued for execution.

**Comment by Xeais** [comment]
@ncesario-lunarg, @jeremyg-lunarg | Is there any news concerning this, slowly but surely annoying, case?

**Comment by jeremyg-lunarg** [comment]
Sorry, I don't see anything else obvious to try based on what you've provided.  Is it possible for you to send us a gfxreconstruct replay file, or something else that would let us reproduce and debug the problem on our end?

**Comment by ncesario-lunarg** [comment]
I may just be parsing this wrong, but I still don't quite understand the queue family ownership transfer here, specifically with the `(src|dst)QueueFamilyIndex` fields for the memory barriers. It looks like something similar to the following is currently happening:
```
Graphics submit
- barrier(src = TRANSFER, dst = GRAPHICS)
- signal(GRAPHICS_SEM)

Transfer submit
- wait(GRAPHICS_SEM)
- barrier(src = TRANSFER, dst = GRAPHICS)

Transfer submit
- copy
- copy
- barrier(src = TRANSFER, dst = GRAPHICS)
- signal(TRANSFER_SEM)
```

i.e, the src family index appears to _always_ be transfer and the dst appears to _always_ be graphics. This seems wrong. I would have expected something along the lines of:
```
Graphics submit
- barrier(src = GRAPHICS, dst = TRANSFER) // release buffers from graphics queue
- signal(GRAPHICS_SEM)

Transfer submit
- wait(GRAPHICS_SEM)
- barrier(src = GRAPHICS, dst = TRANSFER) // acquire buffers from graphics queue
- copy
- copy
- barrier(src = TRANSFER, dst = GRAPHICS) // done with transfer queue, release buffers from transfer queue
- signal(TRANSFER_SEM)

Graphics submit
- wait(TRANSFER_SEM)
- barrier(src = TRANSFER, dst = GRAPHICS) // need to acquire buffers before using them on the graphics queue
- ...
```

**Comment by Xeais** [comment]
@ncesario-lunarg, @jeremyg-lunarg | I have updated the code (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2862#issuecomment-854200032) once more; Nate's last post was very useful.

First, the good news: The release barrier problem is finally gone! Unfortunately, another problem emerged (the two errors are closely linked):
> validation[0]: validation error: [ vuid-vkbegincommandbuffer-commandbuffer-00049 ] object 0: handle = 0x1a435f17ee8, type = vk_object_type_command_buffer; | messageid = 0x84029a9f | calling vkbegincommandbuffer() on active vkcommandbuffer 0x1a435f17ee8[] before it has completed. you must check command buffer fence before this call. the vulkan spec states: commandbuffer must not be in the recording or pending state

> validation[0]: validation error: [ vuid-vkbegincommandbuffer-commandbuffer-00050 ] object 0: handle = 0x1a435f17ee8, type = vk_object_type_command_buffer; object 1: handle = 0x36eb3a0000000156, type = vk_object_type_command_pool; | messageid = 0xb24f00f5 | call to vkbegincommandbuffer() on vkcommandbuffer 0x1a435f17ee8[] attempts to implicitly reset cmdbuffer created from vkcommandpool 0x36eb3a0000000156[] that does not have the vk_command_pool_create_reset_command_buffer_bit bit set. the vulkan spec states: if commandbuffer was allocated from a vkcommandpool which did not have the vk_command_pool_create_reset_command_buffer_bit flag set, commandbuffer must be in the initial state

The HERE-comment in the code above marks the position that triggers the first error. The place (I don't see a problem there!) makes this rather easy error nasty.

Thank you very much for the assistance!

**Comment by ncesario-lunarg** [comment]
for 00049, it looks like you are trying to begin recording commands to a command buffer that is "in flight." i.e., the line immediately preceding the `HERE` comment submits the command buffer, and you have to wait for that command buffer to finish before you start recording to it again. From 6.1 [Command Buffer Lifecycle](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap6.html#commandbuffers-lifecycle):
> Queue submission of a command buffer changes the state of a command buffer from the executable state to the pending state. Whilst in the pending state, applications must not attempt to modify the command buffer in any way - as the device may be processing the commands recorded to it. Once execution of a command buffer completes, the command buffer either reverts back to the executable state, or if it was recorded with VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, it moves to the invalid state. **A synchronization command should be used to detect when this occurs.**

i.e., you'll need to use something like a fence or `vkWaitSemaphores` before the "begin" command at `// HERE` to ensure the command buffer is no longer pending. However, is there a reason you need to break up the transfer commands into multiple submissions inside `ChunkMesh::Upload`? I'm not sure why a single begin/end/submit wouldn't work in this scenario. If these methods are getting called "continuously" ever frame, you might need/want some synchronization mechanism before every "command buffer begin."

**Comment by Xeais** [comment]
@jeremyg-lunarg, @ncesario-lunarg
> However, is there a reason you need to break up the transfer commands into multiple submissions inside `ChunkMesh::Upload`? I'm not sure why a single begin/end/submit wouldn't work in this scenario.

The reason for the break up is this:
> Validation Error: [ UNASSIGNED-CoreValidation-DrawState-NoEndCommandBuffer ] Object 0: handle = 0x20a2eed1378, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xe2982ebe | You must call vkEndCommandBuffer() on VkCommandBuffer 0x20a2eed1378[] before this call to vkQueueSubmit!
---
> If these methods are getting called "continuously" ever frame, you might need/want some synchronization mechanism before every "command buffer begin."

That's not really what I wanted to hear. 😉

What would you recommend for such a case? Could you provide a short code example?

**Comment by ncesario-lunarg** [comment]
I think that VUID primarily (only?) shows up if you try to submit a command buffer before calling `vkEndCommandBuffer`; not 100% sure though. I think if you effectively just get rid of the first transfer queue submission, that should go away. i.e., something like:
```cpp
{ // Graphics command to release buffers
    commandBufferGraphics.Begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);
    m_allocation.ReleaseFrom(commandBufferGraphics, QueueFamOwnershipTransf::Graphics);
    commandBufferGraphics.End();
}


{ // Graphics submission to release buffers
    VkSubmitInfo graphicsSubmitInfo {VK_STRUCTURE_TYPE_SUBMIT_INFO};;
    graphicsSubmitInfo.commandBufferCount = 1;
    graphicsSubmitInfo.pCommandBuffers = &commandBufferGraphics.GetVkCB();
    graphicsSubmitInfo.signalSemaphoreCount = 1;
    graphicsSubmitInfo.pSignalSemaphores = &*semaphoreGraphics;
    vulkan.queues[QUEUE_FAMILY_GRAPHICS]->Submit(1, &graphicsSubmitInfo, *fenceGraphics);
}

commandBufferTransfer.Begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);

{ // Transfer commands to acquire buffers
    m_allocation.AcquireFrom(commandBufferTransfer, QueueFamOwnershipTransf::Graphics);
}

{ // Transfer commands to copy to buffers
    const uint64_t verticesBytes {sizeof(Vertex) * m_allocation.GetNumVertices()};
    const uint64_t indicesBytes {sizeof(uint32_t) * m_allocation.GetNumIndices()};
      
    const VkBufferCopy vertexBufferCopy {0, m_allocation.GetVertexOffset() * sizeof(Vertex), verticesBytes};
    commandBufferTransfer.CopyBuffer(srcBuffer, m_allocation.GetVertexBuffer(), vertexBufferCopy);
      
    const VkBufferCopy indexBufferCopy {verticesBytes, m_allocation.GetIndexOffset() * sizeof(uint32_t), indicesBytes};
    commandBufferTransfer.CopyBuffer(srcBuffer, m_allocation.GetIndexBuffer(), indexBufferCopy);
}

{ // Transfer commands to release buffers
    m_allocation.ReleaseFrom(commandBufferTransfer, QueueFamOwnershipTransf::Transfer);
}

commandBufferTransfer.End();

{ // Transfer submission with commands to acquire, copy, and release buffers, and wait/signal appropriate semaphores
    transferSubmitInfo = {}; //Clear an already used variable.
    transferSubmitInfo.sType = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    transferSubmitInfo.commandBufferCount = 1;
    transferSubmitInfo.pWaitSemaphores = &*semaphoreGraphics;
    transferSubmitInfo.pWaitDstStageMask = &stageFlag;
    transferSubmitInfo.pCommandBuffers = &commandBufferTransfer.GetVkCB();
    transferSubmitInfo.signalSemaphoreCount = 1;
    transferSubmitInfo.pSignalSemaphores = &*semaphoreTransfer;
    vulkan.queues[QUEUE_FAMILY_TRANSFER]->Submit(1, &transferSubmitInfo, *fenceTransfer2);
}

{ // Graphics command to acquire buffers
    commandBufferGraphics.Begin(VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT);
    m_allocation.AcquireFrom(commandBufferGraphics, QueueFamOwnershipTransf::Transfer);
    commandBufferGraphics.End();
}
```

As far as examples go, it might be a good idea use the following resources to post some questions:
- https://www.reddit.com/r/vulkan
- www.khr.io/slack
- https://discord.com/invite/tFdvbEj

I'm going to close this out for now as it's not clear there is a VVL issue to resolve, but please re-open if you feel that is in error.

**Comment by Xeais** [comment]
@ncesario-lunarg, @jeremyg-lunarg | To conclude this, I have updated the code (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2862#issuecomment-854200032) one last time with the working code.

Thank you again for the help - you were great.

**Comment by ncesario-lunarg** [comment]
You're welcome!
